### PR TITLE
[WIP] Drf2 code removal

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by auvipy** [comment]
@sheppard review? suggested edits?

**Comment by sheppard** [comment]
A few more changes:
 * [ ] Remove `USE_LIST_SERIALIZERS` variable
 * [ ] Remove Django 1.6 compatibility from `tests/__init__.py`
 * [ ] Remove `# DRF 3` comments and any remaning `# DRF 2` sections
 * [ ] Make sure the tests pass

**Comment by auvipy** [comment]
thanks will update accordingly

**Comment by sheppard** [comment]
I wrapped this up in 17954b978f02c2bec16c43f47ee28cc003b61422, thanks.

**Pull request closed without merging**
