### PR TITLE
Update supported versions

### PR DESCRIPTION
**Pull request by auvipy**
added python 3.5
updated django and drf min versions
modified setup.py
upgraded pandas version
removed django 1.7 and drf 2.x

### CODE REVIEW

**Comment by auvipy** [comment]
https://github.com/wq/django-rest-pandas/pull/24

**Comment by auvipy** [comment]
@sheppard

**Comment by sheppard** [comment]
Thanks, I'll take a look at merging this tomorrow and then you should be able to get the build for #24 passing.  If you could restore the lint build that would help get this one in:
```yaml
    - DJANGO="django==1.9.4" REST="djangorestframework==3.3.3" LINT=1
```
The reason it's failing is due to some stricter rules added to flake8 since the last build.  It looks like just some minor fixes are needed to meet the new rules.

Also, I'd probably keep the pandas dependency in setup.py at 0.13 even though we're not testing it.  A loose dependency makes it easier when installing on distributions that provide their own slightly-outdated pandas lib.  (I think the only reason I have a minimum at all is due to the use of `boxplot_stats` which was added in 0.13).

**Comment by auvipy** [comment]
Owh OK will try to adjust according to your suggestions

**Comment by auvipy** [comment]
OKish?

**Comment by sheppard** [comment]
This works, thanks.  I merged and fixed the lint error.

**Pull request merged**
